services:
    swbuild-24.04:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user_list: ${user_list}
                docker_gid: ${docker_gid}
        image: swbuild-ubuntu-24.04 
        container_name: swbuild-ubuntu-24.04
        restart: on-failure
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - TZ=Europe/London
            - DEBIAN_FRONTEND=noninteractive
            - VCPKG_ROOT=/opt/vcpkg
        volumes:
            - homedir:/home
            - appsdir:/opt/apps
            - buildcachedir:/opt/cache
        hostname: swbuild-2404
        ports:
          - 8024:8024
          - 2224:2224
        tty: true
volumes:
    homedir:
    appsdir:
    buildcachedir:
