#·Composing IMG DDK build environment
FROM ubuntu:22.04@sha256:da5fdf346e5313bef2a3dd2476c0251d48103213a5e3a0cb3afbb8909f3cf50f
LABEL maintainer="andrei.mironenko@gmail.com"
ENV REFRESHED_AT 2024-06-17
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

#ARG uid
#ARG gid
#ARG username
ARG user_list
ARG docker_gid

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install apt-utils
# Set locales to en_US.UTF-8

RUN apt-get -y install locales
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8
RUN export LANG=en_US.UTF-8

RUN apt-get -y install vim
RUN apt-get -y install nano
RUN apt-get -y install rsync
RUN apt-get -y install zip
RUN apt-get -y install tree

RUN apt-get -y install ninja-build
RUN apt-get -y install build-essential
RUN apt-get -y install bison flex gawk gcc g++ llvm m4 patch
RUN apt-get -y install make ninja-build pkg-config tar zip
RUN apt-get -y install automake bc dpkg-dev libelf-dev libncurses5-dev
RUN apt-get -y install libssl-dev  perl texinfo
RUN apt-get -y install wget xutils-dev

RUN apt-get -y install libdrm-dev libunwind-dev zlib1g-dev
RUN apt-get -y install autopoint gettext gperf intltool libglib2.0-dev
RUN apt-get -y install libltdl-dev libtool 
RUN apt-get -y install git-all
RUN apt-get -y install xfonts-utils xsltproc x11-xkb-utils
RUN apt-get -y install gcc-multilib g++-multilib
RUN apt-get -y install clang
RUN apt-get -y install libclang1 

# Install python3
RUN apt-get -y install python3 python3-libxml2 python3-mako python3-pip python3-git python3-clang
RUN apt-get -y install python-is-python3


# Graphics related packages
#RUN pip3 install  --trusted-host pypi.org  --trusted-host files.pythonhosted.org meson
#RUN apt-get -y install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
#RUN apt-get -y install libxrandr-dev libxi-dev
#RUN apt-get -y install mesa-common-dev opencl-headers

RUN apt-get -y install iputils-ping

RUN apt-get -y install openssh-server openssh-client openssl
RUN apt-get -y install  net-tools iproute2

RUN apt-get -y install openjdk-11-jdk
RUN apt-get -y install screen
RUN apt-get -y install tmux

RUN apt-get -y install libstb-dev
RUN apt-get -y install curl

RUN apt-get -y install expect
RUN apt-get -y install indent
RUN apt-get -y install gpg ca-certificates wget

# Packages required by Ycto
RUN apt-get -y install chrpath cpio diffstat liblz4-tool pigz zstd
RUN apt-get -y install git-lfs gfortran 
RUN apt-get -y install libgnutls28-dev

# Source code indexing tools
RUN apt-get -y install universal-ctags cscope 
# Patch generation tool
RUN apt-get -y install quilt
# Unix man-pages generator from markdown files 
RUN apt-get -y install ronn

# Install bash-completion tool
RUN apt-get -y install bash-completion

# Install kas tool, it's similar to Google repo and it can retrive multiple git repositories 
# but its Yocto specific
RUN pip3 install kas

# Create docker group
RUN groupadd -g ${docker_gid} docker 

# The code below recreates all local users and groups in the container.
# The user_list variable is a comma-separated list of users in the format 
# username:groupname:uid:gid
# For example: "user1:group1:1000:1000,user2:group2:1001:1001"
# It is retrived from the .env file which is generated by makeenv.sh script 
# and read by docker-compose during build.

RUN IFS=','; for entry in ${user_list}; do \
      uname=$(echo $entry | cut -d: -f1); \
      gname=$(echo $entry | cut -d: -f2); \
      uid=$(echo $entry | cut -d: -f3); \
      gid=$(echo $entry | cut -d: -f4); \
      if ! getent group | awk -F: -v id="$gid" '$3 == id' | grep -q . ; then groupadd -g "$gid" "$gname"; fi; \
      if ! id -u $uname >/dev/null 2>&1; then useradd -u "$uid" -g "$gid" "$uname" && usermod -aG docker "$uname"; fi; \
    done

RUN sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking accept-new/' /etc/ssh/ssh_config

# setting repository for getting latest version of the CMake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null

RUN apt-get -y update
# RUN apt-get -y install vulkan-sdk
RUN apt-get -y upgrade cmake

# Change from Ubuntu default dash shell to bash
RUN ln -sf bash /bin/sh

# install vcpkg
ENV appsdir="/opt/apps"
ENV vcpkgdir="${appsdir}/vcpkg"
ENV repodir="${appsdir}/repo"
RUN mkdir -p ${appsdir} 
RUN chown -R root:docker ${appsdir} 
RUN awk -v path="${vcpkgdir}" -F= -i inplace '/^PATH/ { gsub(/"/, "", $2); print $1 FS "\"" $2 ":" path "\""; next } 1' /etc/environment
RUN awk -v path="${repodir}" -F= -i inplace '/^PATH/ { gsub(/"/, "", $2); print $1 FS "\"" $2 ":" path "\""; next } 1' /etc/environment

# set permission for /opt/cache, which is the docker volume buildcachedir
ENV buildcachedir="/opt/cache"
RUN mkdir -p ${buildcachedir}
RUN chown root:${docker_gid} ${buildcachedir}

# Start SSH server
EXPOSE 22


RUN git clone https://github.com/Microsoft/vcpkg.git ${vcpkgdir} 
RUN /opt/apps/vcpkg/bootstrap-vcpkg.sh

RUN git clone https://gerrit.googlesource.com/git-repo ${repodir}

RUN chown -R root:docker ${appsdir}


WORKDIR /
# Copy the script to list users and groups
COPY entrypoint.sh /usr/local/bin/docker_entrypoint.sh
RUN chmod +x /usr/local/bin/docker_entrypoint.sh
ENTRYPOINT [ "/usr/local/bin/docker_entrypoint.sh" ]
CMD /etc/init.d/ssh start && /bin/bash